// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// computev
arma::vec computev(int Locn, double Locsig, double Lockappa);
RcppExport SEXP _vweights_computev(SEXP LocnSEXP, SEXP LocsigSEXP, SEXP LockappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Locn(LocnSEXP);
    Rcpp::traits::input_parameter< double >::type Locsig(LocsigSEXP);
    Rcpp::traits::input_parameter< double >::type Lockappa(LockappaSEXP);
    rcpp_result_gen = Rcpp::wrap(computev(Locn, Locsig, Lockappa));
    return rcpp_result_gen;
END_RCPP
}
// computepnclu
arma::vec computepnclu(int Locn, double Locsig, double Lockappa);
RcppExport SEXP _vweights_computepnclu(SEXP LocnSEXP, SEXP LocsigSEXP, SEXP LockappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Locn(LocnSEXP);
    Rcpp::traits::input_parameter< double >::type Locsig(LocsigSEXP);
    Rcpp::traits::input_parameter< double >::type Lockappa(LockappaSEXP);
    rcpp_result_gen = Rcpp::wrap(computepnclu(Locn, Locsig, Lockappa));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vweights_computev", (DL_FUNC) &_vweights_computev, 3},
    {"_vweights_computepnclu", (DL_FUNC) &_vweights_computepnclu, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_vweights(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
