# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the weights
#'
#' @param Locn Number of observation
#' @param Locsig Sigma parameter
#' @param Lockappa Kappa parameter
#' @return vector of length Locn
#' @export
computev <- function(Locn, Locsig, Lockappa) {
    .Call('_vweights_computev', PACKAGE = 'vweights', Locn, Locsig, Lockappa)
}

#' Computes the prior probability mass function for the number of clusters
#'
#' @param Locn Number of observation
#' @param Locsig Sigma parameter
#' @param Lockappa Kappa parameter
#' @return vector of length Locn
#' @export
computepnclu <- function(Locn, Locsig, Lockappa) {
    .Call('_vweights_computepnclu', PACKAGE = 'vweights', Locn, Locsig, Lockappa)
}

